<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="SSH.NET" Version="2026.0.0" />
    <PackageReference Include="Testcontainers.MongoDb" Version="4.13.0" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.13.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EtlTool.Infrastructure\EtlTool.Infrastructure.csproj" />
    <ProjectReference Include="..\EtlTool.Web\EtlTool.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\test-data\clean.csv"
             Link="TestData\clean.csv"
             CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\test-data\dirty.csv"
             Link="TestData\dirty.csv"
             CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\test-data\clean.xlsx"
             Link="TestData\clean.xlsx"
             CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\test-data\performance-100k.csv"
             Link="TestData\performance-100k.csv"
             CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
